### ISSUE TITLE
可以自适应通知已填写邮箱用户吗

### ISSUE THREAD

**Issue by sli1989** [zhaojun1998/Valine-Admin#4]
感谢博主的分享，但使用后有几个问题

- 非`_user`字段的邮箱地址第一次会收到来自 do-not-reply@apps.leancloud.cn 的验证 GITHUB 的帐号邮箱邮件。不通过验证有啥影响？

- 无法识别at功能？提醒邮件中没有at上下文，应用日志中显示`这条评论没有 @ 任何人`。[live demo](http://saili.science/2017/04/02/github-for-win/#comments)

```
TESTADMIN 发表评论：
@TESTQQ 
站长邮箱评论测试。
```

- 好像无法给邮箱评论用户发提醒？可以同时通知`TO_EMAIL`字段邮箱地址和邮箱评论用户的地址吗？
- 如何辨识是站长回复的？通过邮箱地址吗？

**Comment by zhaojun1998** [comment]
问题1 ： 收到 `do-not-reply@apps.leancloud.cn ` 的邮件是因为你之前配置的 Valine 的默认邮件通知影响了，具体参照 Valine 文档，应该只需要把 Valine 的配置中的 `notify` 参数改为 `false` 即可。

问题2 ：识别 at 功能，请检查你的 Valine 是否是官网版本，我大概看了你的博客，你这个应该不是官方版或不是最新版，请尝试切换到 Valine 最新版再试。

问题3 和 问题4 ：

首先邮件分类 2 种 :  `站长邮件` 和 `游客邮件`，（*可能这种描述不是很准确，但应该可以说明问题*）。

判断站长的方式 ： 根据评论留下的邮件是否与 `SMTP_USER` 或 `TO_EMAIL` 字段其中之一相符，是则判定为是站长。

整体逻辑流程图：

![http://cdn.jun6.net/201806251830_877.png](http://cdn.jun6.net/201806251830_877.png)

草图，还请见谅。

**Comment by sli1989** [comment]
感谢回复。

**Comment by zhaojun1998** [comment]
@sli1989 不客气，你对此有疑问，说明我的 `README` 写的不够完善，我会继续完善。对此项目还有什么建议或疑问，欢迎再次提出。

**Comment by sli1989** [comment]
可是valine版本是自动升级的。最新版是1.1.9呀。

```
valine:
  enable: true #false
  appid: uIrzS1i60S024CvU6ATzr4y7-gzGzoHsz # your leancloud application appid
  appkey: 9o0rnB856nyqXPURwBBncFkR # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Leave your email, just comment here... # comment box placeholder
  avatar: wavatar # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size
```

我试过好几次邮箱配置了，都没有识别出at和站长。
